version: '3.4'

services:
  carbookingservice:
    environment:
        ConnectionStrings__DefaultConnection: Server=db,1433;Database=CarBooking;User Id=sa;Password=yourStrong(!)Password;
    image: florian4300/csharp_carbooking
    ports: 
        - 5000:5000
    depends_on:
        - db
  db:
      image: "mcr.microsoft.com/mssql/server"
      environment:
          SA_PASSWORD: "yourStrong(!)Password"
          ACCEPT_EULA: "Y"
      ports: 
            - 1433:1433
